### ISSUE TITLE
[Bug]: Graph fails to load when viewing a specific professor

### ISSUE THREAD

**Issue by Jake3231** [UTDNebula/utd-trends#119] opened 2023-10-26 01:31 UTC
### What did you expect to happen?

I expect that when viewing any professor or course, the chat will show correctly.

### What happened?

When viewing `MATH 2418 Luis Felipe`, the grade chart fails to appear and shows "An error occurred! Please reload the page, and if this problem persists, contact Nebula Labs."

https://utd-trends-2ognnlrat-utdnebula.vercel.app/dashboard?searchTerms=MATH+2418+Luis+Felipe

### Version

Beta 0.1.0

### What browsers are you seeing the problem on?

Safari

### Relevant log output

```shell
[Error] Nebula API – Error: error
Error: error(anonymous function) — dashboard-7a5ed2a5d2f9e45d.js:1:30865
	(anonymous function) (dashboard-7a5ed2a5d2f9e45d.js:1:32992)

Failed to load resource: the server responded with a status of 400 () https://utd-trends-2ognnlrat-utdnebula.vercel.app/api/grades?prefix=MATH&number=2418&professorName=Luis%20Felipe
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jake3231** [comment] 2023-11-13 22:12
Still hitting this on Production as of 11/13/2023. Is this a known issue?

**Comment by jpahm** [comment] 2023-11-18 03:54
This, alongside other related issues, should be fixed now. The primary issue was caused by the school retroactively updating old course data, with a secondary smaller issue being a small parsing error in the professor names.

**Closed** 2023-12-04 06:17 UTC
Labels: Type: Bug Report
